# fly.toml app configuration file generated for vlaskz-converter-solution on 2023-07-05T22:38:20-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "vlaskz-converter-solution"
primary_region = "gru"

[build]
  image = "vlaskz/common:v1"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
